 name: CI/CD web-app

 on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
 jobs:
  build:
    runs-on: ubuntu-latest

# 1)check repository for Dockerfile
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

# 2)Build docker image using Dockerfile. (This will create an image in Docker root directory)      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
       image: Docker-hub-repo/image-name
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       push: true
       tags: dleeplatinum/web-app
